version: '3.3'
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "rp-node-0:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "redpanda"
  redpanda:
    # image: vectorized/redpanda:v21.6.1
    image: vectorized/redpanda:latest
    container_name: rp-node-0
    entrypoint:
      - /usr/bin/rpk
      - redpanda
      - start
      - --smp=2
      - --memory=4G
      - --overprovisioned
      - --default-log-level=info
      - --node-id=0
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,DOCKER://redpanda:9092,OUTSIDE://redpanda:9093
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,DOCKER://redpanda:9092,OUTSIDE://127.0.0.1:9093
    ports:
      - 9092:9092
      - 9093:9093
      - 29092:29092
    volumes:
      - /var/lib/redpanda/data
  singlestore:
    image: singlestore/cluster-in-a-box:centos-7.3.11-f7c82b8166-3.2.9-1.11.5
    container_name: s2-agg-0
    # volumes:
    #   # persist data between runs:
    #   - /var/lib/memsql
    #   - ./schema.sql:/init.sql:ro
    #   - ./data:/data:ro
    #   - ./data/metrics/singlestore_exporter.cnf:/etc/memsql/memsql_exporter.cnf:ro
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      - ROOT_PASSWORD=something
      - LICENSE_KEY=something
      - START_AFTER_INIT=Y